// src/data/tableData.ts
export interface Row {
  id: number;
  propertyName: string;
  address: string;
  phone: string;
  businessHours: string;
  category: string;
  website: string;
  mismatched: number;
  missing: number;
  lastUpdate: string;
}

export const initialRows: Row[] = [
  {
    id: 1,
    propertyName: "Hollywood",
    address: "2928 Northwest 1st Ave, Miami, FL 33127",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment Complex",
    website: "Available",
    mismatched: 2,
    missing: 2,
    lastUpdate: "06/25/2025 11:23 AM",
  },
  {
    id: 2,
    propertyName: "The Nines at Wellesley",
    address: "50 Stoneview Trail, Lithia, GA 30047",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment building",
    website: "Available",
    mismatched: 0,
    missing: 2,
    lastUpdate: "06/25/2025 11:23 AM",
  },
  {
    id: 3,
    propertyName: "Broadway",
    address: "50 Stoneview Trail, Lithia, GA 30047",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment Rental Agency",
    website: "Available",
    mismatched: 5,
    missing: 1,
    lastUpdate: "06/25/2025 11:23 AM",
  },
  {
    id: 4,
    propertyName: "Buckhead Village",
    address: "728 South 89th East Ave, Tulsa, OK 74133",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment Complex",
    website: "Available",
    mismatched: 7,
    missing: 7,
    lastUpdate: "06/25/2025 11:23 AM",
  },
  {
    id: 5,
    propertyName: "Hollywood",
    address: "4820 Ambassador Way, Austin, TX 78754",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment building",
    website: "Available",
    mismatched: 2,
    missing: 2,
    lastUpdate: "06/25/2025 11:23 AM",
  },
  {
    id: 6,
    propertyName: "The Nines at Wellesley",
    address: "2828 Northwest 1st Ave, Miami, FL 33127",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment Rental Agency",
    website: "Available",
    mismatched: 0,
    missing: 0,
    lastUpdate: "06/25/2025 11:23 AM",
  },
  {
    id: 7,
    propertyName: "Broadway",
    address: "50 Stoneview Trail, Lithia, GA 30047",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment Complex",
    website: "Available",
    mismatched: 6,
    missing: 6,
    lastUpdate: "06/25/2025 11:23 AM",
  },
  {
    id: 8,
    propertyName: "Buckhead Village",
    address: "728 South 89th East Ave, Tulsa, OK 74133",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment building",
    website: "Available",
    mismatched: 8,
    missing: 8,
    lastUpdate: "06/25/2025 11:23 AM",
  },
  {
    id: 9,
    propertyName: "Hollywood",
    address: "4820 Ambassador Way, Austin, TX 78754",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment Rental Agency",
    website: "Available",
    mismatched: 9,
    missing: 9,
    lastUpdate: "06/25/2025 11:23 AM",
  },
  {
    id: 10,
    propertyName: "The Nines at Wellesley",
    address: "2828 Northwest 1st Ave, Miami, FL 33127",
    phone: "+1234567890",
    businessHours: "Present",
    category: "Apartment Complex",
    website: "Available",
    mismatched: 1,
    missing: 1,
    lastUpdate: "06/25/2025 11:23 AM",
  },
];

export const generateMoreRows = (lastId: number): Row[] => {
  return [
    {
      id: lastId + 1,
      propertyName: "Seaside Villas",
      address: "101 Ocean Drive, Santa Monica, CA 90401",
      phone: "+1234567891",
      businessHours: "Present",
      category: "Apartment Complex",
      website: "Available",
      mismatched: 1,
      missing: 2,
      lastUpdate: "06/25/2025 11:23 AM",
    },
    {
      id: lastId + 2,
      propertyName: "Sunset Grove",
      address: "234 Palm Avenue, Tampa, FL 33602",
      phone: "+1234567892",
      businessHours: "Present",
      category: "Apartment building",
      website: "Available",
      mismatched: 0,
      missing: 0,
      lastUpdate: "06/25/2025 11:23 AM",
    },
    {
      id: lastId + 3,
      propertyName: "Riverfront Residences",
      address: "89 River Street, Chicago, IL 60601",
      phone: "+1234567893",
      businessHours: "Present",
      category: "Apartment Rental Agency",
      website: "Available",
      mismatched: 4,
      missing: 1,
      lastUpdate: "06/25/2025 11:23 AM",
    },
    {
      id: lastId + 4,
      propertyName: "Hilltop Apartments",
      address: "765 Green Hill Rd, Denver, CO 80202",
      phone: "+1234567894",
      businessHours: "Present",
      category: "Apartment Complex",
      website: "Available",
      mismatched: 3,
      missing: 2,
      lastUpdate: "06/25/2025 11:23 AM",
    },
    {
      id: lastId + 5,
      propertyName: "Pinewood Estates",
      address: "456 Pine Lane, Seattle, WA 98101",
      phone: "+1234567895",
      businessHours: "Present",
      category: "Apartment building",
      website: "Available",
      mismatched: 0,
      missing: 0,
      lastUpdate: "06/25/2025 11:23 AM",
    },
    {
      id: lastId + 6,
      propertyName: "Lakeview Towers",
      address: "678 Lakeside Blvd, Orlando, FL 32801",
      phone: "+1234567896",
      businessHours: "Present",
      category: "Apartment Rental Agency",
      website: "Available",
      mismatched: 2,
      missing: 5,
      lastUpdate: "06/25/2025 11:23 AM",
    },
    {
      id: lastId + 7,
      propertyName: "Green Meadows",
      address: "321 Meadow Street, Austin, TX 73301",
      phone: "+1234567897",
      businessHours: "Present",
      category: "Apartment Complex",
      website: "Available",
      mismatched: 1,
      missing: 1,
      lastUpdate: "06/25/2025 11:23 AM",
    },
    {
      id: lastId + 8,
      propertyName: "City Central Lofts",
      address: "910 Main St, Atlanta, GA 30303",
      phone: "+1234567898",
      businessHours: "Present",
      category: "Apartment building",
      website: "Available",
      mismatched: 3,
      missing: 4,
      lastUpdate: "06/25/2025 11:23 AM",
    },
    {
      id: lastId + 9,
      propertyName: "Palm Heights",
      address: "789 Sunset Blvd, Los Angeles, CA 90028",
      phone: "+1234567899",
      businessHours: "Present",
      category: "Apartment Rental Agency",
      website: "Available",
      mismatched: 6,
      missing: 0,
      lastUpdate: "06/25/2025 11:23 AM",
    },
    {
      id: lastId + 10,
      propertyName: "Oceanview Retreat",
      address: "303 Shoreline Drive, San Diego, CA 92101",
      phone: "+1234567890",
      businessHours: "Present",
      category: "Apartment Complex",
      website: "Available",
      mismatched: 0,
      missing: 3,
      lastUpdate: "06/25/2025 11:23 AM",
    },
  ];
};
